### ISSUE TITLE
[Request] Config to turn off Build Mode Indicator

### ISSUE THREAD

**Issue by NielsPilgaard** [Tschipp/Linear#1]
Hey o/

The title pretty much says it all - I'd like a config to turn off the Build Mode Indicator, because I'm not fond of being able to see it all the time. A config option to only display it briefly, when changing, would be great aswell. What do you think? :)

**Comment by Tschipp** [comment]
Yeah I think I can do that

**Comment by NielsPilgaard** [comment]
Thank you :D I'm really enjoying the mod!

**Comment by Tschipp** [comment]
Thanks! Just for clarification, by build mode indicator you just mean the thing in the bottom left corner, and not the thing next to the cursor right?

**Comment by NielsPilgaard** [comment]
Yes :)
