### ISSUE TITLE
[Request] Config to disable all Build Modes

### ISSUE THREAD

**Issue by NielsPilgaard** [Tschipp/Linear#2]
I'd like to request a config to disable all build modes for players, so they can be gradually readded throughout a modpack. 

If there's already a good way to do it, could you point me towards it? :)

**Comment by Tschipp** [comment]
you can do it with crafttweaker:
mods.linear.clearBuildModes(IPlayer player)

**Comment by NielsPilgaard** [comment]
That requires hooking into some event on the very first login of each player for a world, I don't think there's an event to handle that, is there?

**Comment by Tschipp** [comment]
I'm not sure, haven't done much with Crafttweaker.
I will add a config with the default enabled buildmodes.

**Comment by NielsPilgaard** [comment]
Perfect, thanks!
