### ISSUE TITLE
Apparently Linear is contributory to crashing Crafttweaker Server side

### ISSUE THREAD

**Issue by Darkmega18** [Tschipp/Linear#8]
G'day was told by Jared apparently theres a file in this mod called on both server and client with only clientsided code or something which is causing issues with crafttweaker for some reason. Was told to report it here after reporting a recent server side only crash to them. the details are in the linked issue and i think jared linked the file with the weird code in it.

https://github.com/CraftTweaker/CraftTweaker/issues/606

**Comment by Tschipp** [comment]
Doesn’t sound good... I will take a look at it, but will only be able to do that in two weeks.

**Comment by Darkmega18** [comment]
I may have to pospone using linear then for a little if it really is the only thing causing crafttweaker to misfire. But thanks for the heads up, rather than leaving me hanging. :)

**Comment by Tschipp** [comment]
Ok, this is fixed. Sorry for the long wait. Will have update out today.

**Comment by Darkmega18** [comment]
eeexcellent. :D
